config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/mswss.jepl:
      branch: main
      repo: https://github.com/EOSC-synergy/mswss.jepl
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/mswss.jepl git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-ruby-donkey.sh
        container: qc.acc_stealthy-azure-newt
  QC.Doc:
    repos:
      github.com/EOSC-synergy/mswss.jepl find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cardinal-gibbon.sh
        container: qc.doc_cloudy-lime-fowl
      github.com/EOSC-synergy/mswss.jepl git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-apricot-jackal.sh
        container: qc.doc_seedy-goldenrod-beaver
      github.com/EOSC-synergy/mswss.jepl markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-jade-cuttlefish.sh
        container: qc.doc_skimpy-ruby-cichlid
  QC.Lic:
    repos:
      github.com/EOSC-synergy/mswss.jepl licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-corn-coral.sh
        container: qc.lic_zippy-lime-dhole
  QC.Ver:
    repos:
      github.com/EOSC-synergy/mswss.jepl get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-olive-cheetah.sh
        container: qc.ver_skimpy-buff-mouse
timeout: 5400
