config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/mswss.jepl:
      branch: main
      repo: https://github.com/EOSC-synergy/mswss.jepl
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/mswss.jepl git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-cerise-anteater.sh
        container: qc.acc_surly-amethyst-wombat
  QC.Doc:
    repos:
      github.com/EOSC-synergy/mswss.jepl find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-yellow-wolfhound.sh
        container: qc.doc_goopy-amaranth-buzzard
      github.com/EOSC-synergy/mswss.jepl git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-amaranth-schnauzer.sh
        container: qc.doc_gamy-sangria-sheep
      github.com/EOSC-synergy/mswss.jepl markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-cerulean-booby.sh
        container: qc.doc_beady-xanthic-quoll
  QC.Lic:
    repos:
      github.com/EOSC-synergy/mswss.jepl licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-black-falcon.sh
        container: qc.lic_tacky-khaki-bombay
  QC.Ver:
    repos:
      github.com/EOSC-synergy/mswss.jepl get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-salmon-terrier.sh
        container: qc.ver_slimy-cerulean-dragon
timeout: 5400
